[global]
# If True, will show a warning when you run a Streamlit-enabled script via "python my_script.py"
# Default: true
showWarningOnDirectionExecution = true

[Logger]
# Level of Logging: 'error', 'warning', 'info', or 'debug'
# Default: 'info'
level = "debug"



[runner]
# Allows you to type a variable or string by itself in a single line of Python code to write it to the app.
# Default: true
magicEnabled = true 